# Site settings
name: Aljon Novelo
title: Aljon Novelo | Software Engineer
description: a Computer Science student who's into building systems, solving problems with code, and creating impact through tech and community work.
url: https://aanovelo.github.io/
baseurl: ''
email: aanovelo@up.edu.ph
cover: https://aanovelo.github.io/img/og.png
logo: https://aanovelo.github.io/img/emojis/desktop.png
resume: https://aanovelo.github.io/resume.pdf
social:
  - title: email
    url: mailto:aanovelo@up.edu.ph
  - title: github
    url: https://github.com/aanovelo
  - title: linkedin
    url: https://www.linkedin.com/in/aljon-novelo/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
